version: "3.3"

networks:
  sec:

volumes:
  data:

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      - sec

  zuul:
    build:
      context: ./zuul
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      - sec

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      - sec

  item:
    build:
      context: ./item
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      - sec

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      - sec



