version: "3.3"

volumes:
  data:

services:
##mysql配置
  mysql:
    environment:
      ##root账号的密码
      - MYSQL_ROOT_PASSWORD=root123456
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai  
    image: "docker.io/mysql:latest" 
    container_name: mysql
    restart: always
    # command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题 
    command: --default-authentication-plugin=caching_sha2_password #这行代码解决无法访问的问题 
    ##映射挂载
    volumes:
      ##数据目录，要确保先创建好
        - "/data/mysql:/var/lib/mysql"
        ##初始化的脚本，初始化我们存放的init.sql文件
        - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
        - "3306:3306"
    networks:
      rmq:
        aliases:
          - mysql

  ##redis配置
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --appendonly yes --requirepass "root123456"
    ports:
      - "6379:6379"
    volumes:
      ##数据目录，要确保先创建好
      - /data/redis:/data
    environment:  
      - TZ=Asia/Shanghai 
    networks:
      rmq:
        aliases:
          - redis

  rmqnamesrv:
    image: foxiswho/rocketmq:server
    container_name: rmqnamesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./rmq/srv/logs:/opt/logs
      - ./rmq/srv/store:/opt/store
    environment:  
      - TZ=Asia/Shanghai 
    networks:
        rmq:
          aliases:
            - rmqnamesrv
  rmqbroker:
    image: foxiswho/rocketmq:broker
    container_name: rmqbroker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rmq/broker/logs:/opt/logs
      - ./rmq/broker/store:/opt/store
      - ./rmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
        NAMESRV_ADDR: "rmqnamesrv:9876"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
        TZ: Asia/Shanghai
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    restart: always
    ports:
      - 8090:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
        TZ: Asia/Shanghai
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole
  nginx:
    image: 'openresty/openresty'
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
        - TZ=Asia/Shanghai
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/vhost:/etc/nginx/conf.d
      - ./nginx/site:/etc/nginx/site
    networks:
      rmq:
        aliases:
          - nginx
networks:
  rmq:
    # name: rmq
    driver: bridge
    
